<?php

function socialshareprivacy_menu() {

    $items = array();

    $items['admin/settings/socialshareprivacy'] = array(
        'title' => t('Social share privacy'),
        'description' => t('Configure settings for social share privacy'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('socialshareprivacy_admin'),
        'access arguments' => array('access administration pages'),
        'type' => MENU_NORMAL_ITEM,
    );

    return $items;
}

function socialshareprivacy_admin() {
    $form = array();

    $form['socialshareprivacy_services'] = array(
        '#type' => 'checkboxes',
        '#title' => t('Enabled services'),
        '#default_value' => variable_get('socialshareprivacy_services', array('facebook', 'gplus', 'twitter')),
        '#options' => array(
            'facebook' => 'Facebook',
            'twitter' => 'Twitter',
            'gplus' => 'Google Plus',
        ),
    );

    return system_settings_form($form);
}

function _socialshareprivacy_servicestatus($service) {
    $settings = variable_get('socialshareprivacy_services', array('facebook', 'gplus', 'twitter'));
    if (array_key_exists($service, $settings) && $settings[$service] !== 0) {
        return "on";
    }
    return "off";
}

function socialshareprivacy_block_info() {
    return socialshareprivacy_block();
}

function socialshareprivacy_block_view($delta = 0) {
    return socialshareprivacy_block($op='view');
}
function socialshareprivacy_block($op = 'list', $delta = 0, $edit = array()) {
    $block = array();
    if ($op == 'list') {
        $block[0]['info'] = t('Social share privacy');
    }
    elseif ($op == 'view') {
        $block['subject'] = t('Social share privacy');
        $block['content'] = '<div id="socialshareprivacy"></div>';
        $path = drupal_get_path('module', 'socialshareprivacy');
        $imgpath = base_path() . $path;
        $options = "{
        services : {
            facebook : {
                'status' : '" . _socialshareprivacy_servicestatus("facebook") . "',
                'dummy_img' : '$imgpath/socialshareprivacy/images/dummy_facebook.png',
                'app_id' : '234037923313454',
            },
            twitter : {
                'status' : '" . _socialshareprivacy_servicestatus("twitter") . "',
                'dummy_img' : '$imgpath/socialshareprivacy/images/dummy_twitter.png'
            },
            gplus : {
                'status' : '" . _socialshareprivacy_servicestatus("gplus") . "',
                'dummy_img' : '$imgpath/socialshareprivacy/images/dummy_gplus.png'
            },
        },
        'css_path': '$imgpath/socialshareprivacy/socialshareprivacy.css'
        }";
        drupal_add_js($path . '/jquery.socialshareprivacy.js', 'file');
        drupal_add_js('jQuery(document).ready(function () { if(jQuery("#socialshareprivacy").length > 0){
        jQuery("#socialshareprivacy").socialSharePrivacy(' . $options . '); } });', 'inline');
    }

    return $block;
}

